# -*- coding: utf-8 -*-
"""python basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18z4nF3JFZC-ubrHxgsemLJ2XFb5Y9rQc
"""

#Write a program to print the given number is odd or even.

num=int(input())
if (num % 2) == 0:
  print("num is even")
else:
  print("num is odd")

#Write a program to find the given number is positive or negative

number=int(input())
if number>0:
  print("number is positive")
elif number == 0:
  print("number is zero")
else:
  print("number is negative")

#Write a program to find the sum of two numbers.

num1=int(input("enter a number 1: "))
num2 =int(input("enter a number 2: "))
print("Sum of two number: ",num1+num2)

#Write a program to find if the given number is prime or not.

prime=int(input("Enter the number:"))
for i in range(2,prime):
  if prime % i == 0:
    print("not a prime")
    break
else:
  print("it is prime")

#Write a program to check if the given number is palindrome or not.

a=input()
reverse=a[::-1]
if a == reverse:
  print("It is palindrome")
else:
  print("It is not a palindrome")